src/com/ncsts/domain/Cust.java
package com.ncsts.domain;

import java.io.Serializable;
import javax.persistence.*;

import java.util.Date;
import java.util.Set;


/**
 * The persistent class for the TB_CUST database table.
 * 
 */
@Entity
@Table(name="TB_CUST")
public class Cust extends Auditable implements Serializable, Idable<Long> {
	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name="TB_CUST_CUSTID_GENERATOR" , allocationSize = 1, sequenceName="SQ_TB_CUST_ID")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TB_CUST_CUSTID_GENERATOR")
	@Column(name="CUST_ID")
	private Long custId;

	@Column(name="ACTIVE_FLAG")
	private String activeFlag;

	@Column(name="CUST_NAME")
	private String custName;

	@Column(name="CUST_NBR")
	private String custNbr;
	
	@Transient
	private Long entityId;
	
	@Transient
	private String custLocnCode;

	@Transient
	private String custLocnName;

	@Transient
	private String custLocnCountry;

	@Transient
	private String custLocnActiveFlag;
	
	@Transient
	private String custLocnState;
	
	@Transient
	private String lookupFlag;

	public void setCustLocnCountry(String custLocnCountry) {
		this.custLocnCountry = custLocnCountry;
	}

	public String getCustLocnCountry() {
		return this.custLocnCountry;
	}

	public String getCustLocnState() {
		return this.custLocnState;
	}

	public void setCustLocnState(String custLocnState) {
		this.custLocnState = custLocnState;
	}

	public String getCustLocnName() {
		return this.custLocnName;
	}

	public void setCustLocnName(String custLocnName) {
		this.custLocnName = custLocnName;
	}

	public String getCustLocnCode() {
		return this.custLocnCode;
	}

	public void setCustLocnCode(String custLocnCode) {
		this.custLocnCode = custLocnCode;
	}

	public String getCustLocnActiveFlag() {
		return this.custLocnActiveFlag;
	}

	public void setCustLocnActiveFlag(String custLocnActiveFlag) {
		this.custLocnActiveFlag = custLocnActiveFlag;
	}
	
	public String getLookupFlag() {
		return this.lookupFlag;
	}

	public void setLookupFlag(String lookupFlag) {
		this.lookupFlag = lookupFlag;
	}

	//bi-directional many-to-one association to CustEntity
	//@OneToMany(mappedBy="cust")
	//private Set<CustEntity> custEntities;

	//bi-directional many-to-one association to CustLocn
	//@OneToMany(mappedBy="cust")
	//private Set<CustLocn> custLocns;

    public Cust() {
    }
    
    public Long getId() {
		return getCustId();
	}

	public String getIdPropertyName() {
		return "custId";
	}
	
	public void setId(Long id) {
		setCustId(id);
	}

	public Long getCustId() {
		return this.custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCustNbr() {
		return this.custNbr;
	}

	public void setCustNbr(String custNbr) {
		this.custNbr = custNbr;
	}
	
	public Boolean getActiveBooleanFlag() {
    	return "1".equals(this.activeFlag);
	}

	public void setActiveBooleanFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag == Boolean.TRUE ? "1" : "0";
	}
	
	public Boolean getLookupBooleanFlag() {
    	return "1".equals(this.lookupFlag);
	}

	public void setLookupBooleanFlag(Boolean lookupFlag) {
		this.lookupFlag = lookupFlag == Boolean.TRUE ? "1" : "0";
	}
	
	public Long getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	//public Set<CustEntity> getCustEntities() {
	//	return this.custEntities;
	//}

	//public void setCustEntities(Set<CustEntity> custEntities) {
	//	this.custEntities = custEntities;
	//}
	
	//public Set<CustLocn> getCustLocns() {
	//	return this.custLocns;
	//}

	//public void setCustLocns(Set<CustLocn> custLocns) {
	//	this.custLocns = custLocns;
	//}
	
}

src/com/ncsts/view/bean/CustomerLocationBean.java
package com.ncsts.view.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.GregorianCalendar;
import java.util.Hashtable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIInput;
import javax.faces.component.html.HtmlSelectBooleanCheckbox;
import javax.faces.component.html.HtmlSelectOneMenu;
import javax.faces.context.FacesContext;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;

import com.ncsts.services.JurisdictionService;

import org.ajax4jsf.component.html.HtmlAjaxSupport;
import org.apache.log4j.Logger;
import org.richfaces.component.html.HtmlDataTable;
import org.richfaces.component.html.HtmlSimpleTogglePanel;
import org.richfaces.model.selection.SimpleSelection;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.StringUtils;

import com.ncsts.common.CacheManager;
import com.ncsts.domain.CustEntity;
import com.ncsts.domain.CustEntityPK;
import com.ncsts.domain.EntityItem;
import com.ncsts.domain.EntityLevel;
import com.ncsts.domain.Jurisdiction;
import com.ncsts.domain.Cust;
import com.ncsts.domain.CustLocn;
import com.ncsts.domain.User;
import com.ncsts.dto.EntityItemDTO;
import com.ncsts.jsf.model.CustDataModel;
import com.ncsts.jsf.model.CustLocnDataModel;
import com.ncsts.jsf.model.EntityDataModel;
import com.ncsts.services.CustService;
import com.ncsts.services.CustLocnService;
import com.ncsts.services.DriverReferenceService;
import com.ncsts.services.EntityItemService;
import com.ncsts.services.EntityLevelService;
import com.ncsts.services.ListCodesService;
import com.ncsts.services.OptionService;
import com.ncsts.view.util.TogglePanelController;

import javax.faces.event.ValueChangeEvent;
import javax.persistence.Transient;

public class CustomerLocationBean {	
	private Logger logger = Logger.getLogger(CustomerLocationBean.class);

	private Cust filterCust = new Cust();
	private CustLocn filterCustLocn = new CustLocn();
	private Cust selCust = new Cust();
	private CustLocn selCustLocn = new CustLocn();
	private Cust updateCust = new Cust();
	private CustLocn updateCustLocn = new CustLocn();
	private boolean isEntityCheck=false;
	private List<SelectItem> filterStateMenuItems;
	private List<SelectItem> filterCountryMenuItems;
	private List<SelectItem> filterActiveCustomerMenuItems;
	private List<SelectItem> filterActiveLocationMenuItems;
	private List<SelectItem> filterEntityMenuItems;
	
	private String filterJurisdictionHolidayCode;
	private String filterJurisdictionCountry;
	private String filterJurisdictionState;
	private String filterJurisdictionTaxCode;
	private String filterJurisdictionCounty;
	private String filterJurisdictionCity;
	public String entityCode;
	private CommonCallBack commonCallBack;
	
	private List<SelectItem> entityLevelList = null;
	private Map<Long, String > entityLevelMap = null;
	boolean selectAll = false;
	private loginBean loginBean;
	private ExemptionCertificateBean exemptionCertificateBean;
	
	private List<EntityItem> retrieveEntityItemList= new ArrayList<EntityItem>();
	private List<SelectItem> filterJurisdictionCountyMenuItems;
	private List<SelectItem> filterJurisdictionCityMenuItems;
	private CacheManager cacheManager;
	
	private MatrixCommonBean matrixCommonBean;
	
	private CustDataModel custDataModel;
	private EntityDataModel entityDataModel;
	private CustLocnDataModel custLocnDataModel;
	
	private SimpleSelection selection = new SimpleSelection();
	private int selectedCustRowIndex = -1;
	private int selectedCustLocnRowIndex = -1;
	private EditAction currentAction = EditAction.VIEW;
	static final int MAX_SELECT_ALL = 10000;
	private FilePreferenceBackingBean filePreferenceBean;
	private CustService custService;
	private CustLocnService custLocnService;
	private EntityItemService entityItemService; 
	private ListCodesService listCodesService;
	private OptionService optionService;
	private JurisdictionService jurisdictionService;
	protected EntityLevelService entityLevelService;	
	private EntityItemDTO filterEntityItem = null;
	private String lookupFlag;
	private String showhide="";
	private SearchJurisdictionHandler filterHandler = new SearchJurisdictionHandler();
	private HtmlSelectOneMenu countyInput = new HtmlSelectOneMenu();	
	private HtmlSelectOneMenu cityInput = new HtmlSelectOneMenu();
	private Hashtable<Long,CustEntity> updateCustEntityListChecked = new Hashtable<Long,CustEntity>();
	private TogglePanelController togglePanelController = null;
	private TaxJurisdictionBackingBean taxJurisdictionBean;
	
	public TaxJurisdictionBackingBean getTaxJurisdictionBean() {
		return taxJurisdictionBean;
	}

	public void setTaxJurisdictionBean(
			TaxJurisdictionBackingBean taxJurisdictionBean) {
		this.taxJurisdictionBean = taxJurisdictionBean;
	}
	
	public  TogglePanelController getTogglePanelController(){
		if(togglePanelController==null){
			togglePanelController = new TogglePanelController();
			togglePanelController.addTogglePanel("CustomerInformationPanel", true);
			togglePanelController.addTogglePanel("LocationInformationPanel", false);
		}
		return togglePanelController;
	}
	
	public void setTogglePanelController(TogglePanelController togglePanelController){
		this.togglePanelController = togglePanelController;;
	}
	
	@Autowired
	private DriverReferenceService driverReferenceService;
	
	public Cust getSelCust(){
		return selCust;
	}
	
	public String getLookupFlag() {
		return this.lookupFlag;
	}

	public void setLookupFlag(String lookupFlag) {
		this.lookupFlag = lookupFlag;
	}
	
	public CustLocn getSelCustLocn(){
		return selCustLocn;
	}
	
    public void setMatrixCommonBean(MatrixCommonBean matrixCommonBean) {
    	this.matrixCommonBean = matrixCommonBean;
		filterHandler.setJurisdictionService(matrixCommonBean.getJurisdictionService());
		filterHandler.setCacheManager(matrixCommonBean.getCacheManager());
		filterHandler.setTaxJurisdictionBean(taxJurisdictionBean);
		filterHandler.setCallbackScreen("custlocn_update");
	}
	
	public List<SelectItem> getFilterCountryMenuItems() {
		if(filterCountryMenuItems==null){
			filterCustLocn.setCountry("");
		}
		filterCountryMenuItems = getCacheManager().createCountryItems();   
		return filterCountryMenuItems;
	}
	
	public void filterCountryChanged(ValueChangeEvent e){
		String newCountry = (String)e.getNewValue();
		if(newCountry==null) filterCustLocn.setCountry("");
		else filterCustLocn.setCountry(newCountry);
	
		if(filterStateMenuItems!=null) filterStateMenuItems.clear();

		filterStateMenuItems = getCacheManager().createStateItems(filterCustLocn.getCountry());
		filterCustLocn.setState("");
    }
	
	public List<SelectItem> getFilterStateMenuItems() { 
	   if (filterStateMenuItems == null) {
		   filterStateMenuItems = getCacheManager().createStateItems(filterCustLocn.getCountry());
		   filterCustLocn.setState("");
	   }	    
	   return filterStateMenuItems;
	}
	
	public List<SelectItem> getFilterEntityMenuItems() {
		if(filterEntityMenuItems==null){
			List<SelectItem> selectItems = new ArrayList<SelectItem>();
	    	selectItems.add(new SelectItem(new Long(0L),"Select an Entity"));
	    	
	    	List<EntityItem> eList = entityItemService.findAllEntityItems();
    	    if(eList != null && eList.size() > 0){
    	    	for(EntityItem entityItem:eList){
    	    		if(entityItem.getEntityId().intValue()!=0){
    	    			selectItems.add(new SelectItem(entityItem.getEntityId(), entityItem.getEntityCode() + " - " + entityItem.getEntityName()));		
    	    		}
    	    	}
    	    } 	
	    	    
	    	filterEntityMenuItems = selectItems;
		}
 
		return filterEntityMenuItems;
	}
	
	public List<SelectItem> getFilterActiveCustomerMenuItems() {
		if(filterActiveCustomerMenuItems==null){
			List<SelectItem> selectItems = new ArrayList<SelectItem>();
	    	selectItems.add(new SelectItem("","All Customers"));
	    	selectItems.add(new SelectItem("1","Active Only"));
	    	selectItems.add(new SelectItem("0","Inactive Only"));
	   
	    	filterActiveCustomerMenuItems = selectItems;
	    	
			filterCust.setActiveFlag("");
		}
 
		return filterActiveCustomerMenuItems;
	}
	
	public List<SelectItem> getFilterActiveLocationMenuItems() {
		if(filterActiveLocationMenuItems==null){
			List<SelectItem> selectItems = new ArrayList<SelectItem>();
	    	selectItems.add(new SelectItem("","All Locations"));
	    	selectItems.add(new SelectItem("1","Active Only"));
	    	selectItems.add(new SelectItem("0","Inactive Only"));
	   
	    	filterActiveLocationMenuItems = selectItems;
	    	
			filterCustLocn.setActiveFlag("");
		}
 
		return filterActiveLocationMenuItems;
	}
	
	public JurisdictionService getJurisdictionService() {
		return jurisdictionService;
	}

	public void setJurisdictionService(JurisdictionService jurisdictionService) {
		this.jurisdictionService = jurisdictionService;
	}	
	
	public void setFilterJurisdictionHolidayCode(String filterJurisdictionHolidayCode) {
		this.filterJurisdictionHolidayCode = filterJurisdictionHolidayCode;
	}
	
	public String getFilterJurisdictionHolidayCode() {
		return filterJurisdictionHolidayCode;
	}
	
	public void setFilterJurisdictionCountry(String filterJurisdictionCountry) {
		this.filterJurisdictionCountry = filterJurisdictionCountry;
	}
	
	public String getFilterJurisdictionCountry() {
		return filterJurisdictionCountry;
	}
	
	public void setFilterJurisdictionState(String filterJurisdictionState) {
		this.filterJurisdictionState = filterJurisdictionState;
	}
	
	public String getFilterJurisdictionState() {
		return filterJurisdictionState;
	}
	
	public void setFilterJurisdictionCounty(String filterJurisdictionCounty) {
		this.filterJurisdictionCounty = filterJurisdictionCounty;
	}
	
	public String getFilterJurisdictionCounty() {
		return filterJurisdictionCounty;
	}
	

WebRoot/customerLocation/CustLocnLookupMain.jsp
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">

<ui:include src="/customerLocation/CustLocnMain.jsp">
	<ui:param name="handlerBean" value="#{customerLocationLookupBean}"/>
	<ui:param name="showSearchScreen" value="false" />
	<ui:param name="showLookupScreen" value="true" />
</ui:include>
   
</html>

WebRoot/customerLocation/CustLocnSearchMain.jsp
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">

<ui:include src="/customerLocation/CustLocnMain.jsp">
	<ui:param name="handlerBean" value="#{customerLocationSearchBean}"/>
	<ui:param name="showSearchScreen" value="true" />
	<ui:param name="showLookupScreen" value="false" />
</ui:include>
   
</html>

WebRoot/customerLocation/CustLocnUpdate.jsp
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">

<ui:composition template="/WEB-INF/view/templates/standard.xhtml">

<ui:define name="script">
	<script type="text/javascript">
	//<![CDATA[
	//]]>
	</script>
</ui:define>

<ui:define name="body">
<h1><h:graphicImage id="imgCustLocnAdd" alt="Customers&#32;&#38;&#32;Locations" value="/images/headers/hdr-customerLocation-maintenance.gif"  /></h1>

<h:form id="custLocnUpdateForm">
<div id="top">
	<div id="table-one">
	<div id="table-four-top">
		<h:messages errorClass="error" />
	</div>
	<div id="table-one-content" style="height:418px;">
	<table cellpadding="0" cellspacing="0" width="913" id="rollover" class="ruler">
	<thead>
		<tr><td colspan="7"><h:outputText value="#{customerLocationSearchBean.actionText}"/> a Customer Location</td></tr>
	</thead>
	<tbody>			
		<tr><th colspan="7">Customer</th></tr>  
		<tr>
			<td>&#160;</td>
			<td>Number:</td>
			<td style="width:300px;">
				<h:inputText value="#{customerLocationSearchBean.updateCust.custNbr}" 
						disabled="true" id="txtcustNbr" style="width:300px;" /></td>
			<td>&#160;</td>
			<td>&#160;</td>
			<td>&#160;</td>
			<td>&#160;</td>
		</tr>
		<tr>
			<td>&#160;</td>
			<td>Name:</td>
			<td style="width:500px;" colspan="4">
				<h:inputText value="#{customerLocationSearchBean.updateCust.custName}" 
						disabled="true" id="txtcustName" style="width:100%;" /></td>
			<td style="width:40%">&#160;</td>
		</tr>

		<tr><th colspan="7">Location:</th></tr>
		<tr>
			<td>&#160;</td>
			<td>Code:</td>
			<td style="width:300px;" colspan="4">
				<h:inputText id="custLocnCode" value="#{customerLocationSearchBean.updateCustLocn.custLocnCode}" maxlength="40" 
						 disabled="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayUpdateAction or customerLocationSearchBean.displayViewAction}" style="width:300px;" /></td>          
			
			<td>&#160;</td>
		</tr>
		
		<tr>
			<td style="width:50px;">&#160;</td>
			<td>Name:</td>
			<td style="width:500px;" colspan="4">
				<h:inputText id="locationName" value="#{customerLocationSearchBean.updateCustLocn.locationName}" maxlength="50" 
						 disabled="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayViewAction}" style="width:100%;" /></td>
			<td>&#160;</td>
		</tr>
		
		<tr>
			<td style="width:50px;">&#160;</td>
			<td>Address Line 1:</td>
			<td style="width:500px;" colspan="4">
				<h:inputText id="addressLine1" value="#{customerLocationSearchBean.updateCustLocn.addressLine1}" maxlength="50" 
						 disabled="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayViewAction}" style="width:100%;" /></td>
			<td>&#160;</td>
		</tr>
		
		<tr>
			<td style="width:50px;">&#160;</td>
			<td align="right">Line 2:</td>
			<td style="width:500px;" colspan="4">
				<h:inputText id="addressLine2" value="#{customerLocationSearchBean.updateCustLocn.addressLine2}" maxlength="50" 
						 disabled="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayViewAction}" style="width:100%;" /></td>
			<td>&#160;</td>
		</tr>
	
	</tbody>
	</table>
	
	<table cellpadding="0" cellspacing="0" width="100%" id="rollover" class="ruler">
	<tbody>
		<tr>
			<td width="50px" >&#160;</td>
			<td style="align:left;">
			<ui:include src="/WEB-INF/view/components/jurisdiction_screen.xhtml">
				<ui:param name="handler" value="#{customerLocationSearchBean.filterHandler}"/>
				<ui:param name="id" value="jurisInput"/>
				<ui:param name="readonly" value="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayViewAction}"/>
				<ui:param name="showheaders" value="true"/>
				<ui:param name="popupName" value="searchJurisdiction"/>
				<ui:param name="popupForm" value="searchJurisdictionForm"/>
			</ui:include>
			</td>
		</tr>
	</tbody>
	</table>
				
	<table cellpadding="0" cellspacing="0" width="100%" id="rollover" class="ruler">
	<tbody>			
		<tr>
			<td>&#160;</td>
			<td>Active?:</td>
			<td style="width:300px;">	 
				<h:selectBooleanCheckbox id="activeFlagId" 
					disabled="#{customerLocationSearchBean.displayDeleteAction or customerLocationSearchBean.displayViewAction}"
					value="#{customerLocationSearchBean.updateCustLocn.activeBooleanFlag}" styleClass="check"  />
							 
						 </td>
			             
			<td style="width:100%;">&#160;</td>
			<td>&#160;</td>
			<td>&#160;</td>
			<td>&#160;</td>
		</tr>
		
		<tr>
			<td style="width:50px;">&#160;</td>
			<td>Last Update User ID:</td>
			<td style="width:300px;">
				<h:inputText value="#{customerLocationSearchBean.updateCustLocn.updateUserId}" 							 
					 	 disabled="true" id="txtUpdateUserId" style="width:200px;" /></td>        
			<td style="width:100%;">&#160;</td>
			<td>Last Update Timestamp:</td>
			<td style="width:300px;">
				<h:inputText value="#{customerLocationSearchBean.updateCustLocn.updateTimestamp}" 							 
					 	 disabled="true" id="txtUpdateTimestamp" style="width:200px;">
			<f:converter converterId="dateTime"/>
			</h:inputText></td>
			<td>&#160;</td>
		</tr>
	</tbody>
	</table>
	
	</div>
	</div>
	
	<div id="table-four-bottom">
	<ul class="right">
		<li class="ok-add-exemp1"><h:commandLink id="btnOkAddChild" disabled="#{!customerLocationSearchBean.displayAddAction}" value="" action="#{customerLocationSearchBean.addCustLocnExAction}" /></li>
		<li class="ok"><h:commandLink id="btnOk" value="" action="#{customerLocationSearchBean.okCustLocnAction}" /></li>
		<li class="cancel"><h:commandLink id="btnCancel" immediate="true" disabled="#{customerLocationSearchBean.displayViewAction}" action="#{customerLocationSearchBean.cancelAction}" /></li>
	</ul>
	</div>	
	
</div>	

</h:form>

<ui:include src="/WEB-INF/view/components/jurisdiction_search.xhtml">
	<ui:param name="handler" value="#{customerLocationSearchBean.filterHandler}"/>
	<ui:param name="popupName" value="searchJurisdiction"/>
	<ui:param name="popupForm" value="searchJurisdictionForm"/>
	<ui:param name="jurisId" value="jurisId"/>
	<ui:param name="reRender" value="custLocnUpdateForm:jurisInput"/>
</ui:include>

</ui:define>
</ui:composition>
</html>