src/com/ncsts/view/bean/AidFileManagerBean.java
package com.ncsts.view.bean;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.component.html.HtmlSelectBooleanCheckbox;
import javax.faces.context.FacesContext;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.ajax4jsf.component.html.HtmlAjaxSupport;
import org.apache.myfaces.custom.fileupload.HtmlInputFileUpload;
import org.apache.myfaces.custom.fileupload.UploadedFile;
import org.richfaces.component.html.HtmlDataTable;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import com.ncsts.common.CacheManager;
import com.ncsts.common.Util;
import com.ncsts.domain.ListCodes;
import com.ncsts.domain.User;
import com.ncsts.dto.DbPropertiesDTO;
import com.ncsts.dto.ImportSpecDTO;
import com.ncsts.jsf.model.BaseExtendedDataModel;
import com.ncsts.management.DbPropertiesBean;
import com.ncsts.services.ImportDefAndSpecsService;
import com.ncsts.view.util.FacesUtils;
import com.ncsts.view.util.TogglePanelController;

public class AidFileManagerBean {
	private loginBean loginBean;
	private FilePreferenceBackingBean filePreferenceBean;
	private CacheManager cacheManager;
	private ImportDefAndSpecsService importDefAndSpecsService;
	private DbPropertiesBean dbPropertiesBean;
	public String aidRootFolder = "";
	public String selectedDataFolder = "";
	public String selectedSeparator = null;
	public static String IMPORTED_FOLDER = "Imported";
	public static String LOG_FOLDER = "Log";
	public static String SCRIPTS_FOLDER = "Scripts";
	public static String POSTIMPORT_FOLDER = "Post-Import";
	public static String PREIMPORT_FOLDER = "Pre-Import";
	private int selectedSpecRowIndex = -1;
	private int selectedFileRowIndex = -1;
	private List<SelectItem> specTypeList = null;
	private List<SelectItem> specList = null;
	private List<SelectItem> fileDisplayItems;
	private String selectedSpecType = "";
	private String selectedSpec = "";
	private String selectedDescription = "";
	private String selectedName = "";
	private Date selectedAsOfDate;
	private ImportSpecDTO selectedImportSpecDTO = null;
	private FileItem selectedFileItem = null;
	private List<ImportSpecDTO> importSpecList = new ArrayList<ImportSpecDTO>();
	private List<FileItem> fileItemList = new ArrayList<FileItem>();
	private Map<String,String> sortOrder;
	
	private static String QUEUED = "QUEUED";
	private static String IMPORTED = "IMPORTED";
	private static String POSTSCRIPT = "POSTSCRIPT";
	private static String PRESCRIPT = "PRESCRIPT";
	private String selectedFileDisplay = QUEUED;
	
	private String actionText;
	private String fileNameText;
	private String fileContent;
	private String filePrefix;
	
	private HtmlInputFileUpload uploadFile;
	private String uploadedFileName = null;
	private String uploadedFileSize = null;
	
	private int defaultRowNumber = 100;
	
	private TogglePanelController togglePanelController = null;
	
	public void init() {
		aidRootFolder = filePreferenceBean.getAidInstallation();
	}
	
	public User getCurrentUser() {
		return loginBean.getUser();
   }
	
	public  TogglePanelController getTogglePanelController(){
		if(togglePanelController==null){
			togglePanelController = new TogglePanelController();
			togglePanelController.addTogglePanel("AIDFileManagerSPecPanel", true);
			togglePanelController.addTogglePanel("AIDFileManagerFilePanel", false);
		}
		return togglePanelController;
	}
	
	public void setTogglePanelController(TogglePanelController togglePanelController){
		this.togglePanelController = togglePanelController;;
	}
	
	public String getUploadedFileName() {
		return uploadedFileName;
	}

	public void setUploadedFileName(String uploadedFileName) {
		this.uploadedFileName = uploadedFileName;
	}
	
	public String getUploadedFileSize() {
		return uploadedFileSize;
	}

	public void setUploadedFileSize(String uploadedFileSize) {
		this.uploadedFileSize = uploadedFileSize;
	}

	public HtmlInputFileUpload getUploadFile() {
		return uploadFile;
	}

	public void setUploadFile(HtmlInputFileUpload uploadFile) {
		this.uploadFile = uploadFile;
	}

	public String getFilePrefix() {
		return filePrefix;
	}
	
	public String getActionText() {
		return actionText;
	}
	
	public String getFileNameText() {
		return fileNameText;
	}
	
	public String getFileContent() {
		return fileContent;
	}
	
	public int getSelectedSpecRowIndex() {
		return selectedSpecRowIndex;
	}
	
	public void setSelectedSpecRowIndex(int selectedSpecRowIndex) {
		this.selectedSpecRowIndex = selectedSpecRowIndex;
	}
	
	public int getSelectedFileRowIndex() {
		return selectedFileRowIndex;
	}
	
	public void setSelectedFileRowIndex(int selectedFileRowIndex) {
		this.selectedFileRowIndex = selectedFileRowIndex;
	}
	
	public void setDbPropertiesBean(DbPropertiesBean dbPropertiesBean) {
		this.dbPropertiesBean = dbPropertiesBean;
	}
	
	public CacheManager getCacheManager() {
		return this.cacheManager;
	}
	
	public void setCacheManager(CacheManager cacheManager) {
		this.cacheManager = cacheManager;
	}
	
	public ImportDefAndSpecsService getImportDefAndSpecsService() {
		return importDefAndSpecsService;
	}

	public void setImportDefAndSpecsService(
			ImportDefAndSpecsService importDefAndSpecsService) {
		this.importDefAndSpecsService = importDefAndSpecsService;
	}
	
	public Date getSelectedAsOfDate() {
		return selectedAsOfDate;
	}

	public void setSelectedAsOfDate(Date selectedAsOfDate) {
		this.selectedAsOfDate = selectedAsOfDate;
	}
	
	public String getSelectedSpecType() {
		return selectedSpecType;
	}

	public void setSelectedSpecType(String selectedSpecType) {
		this.selectedSpecType = selectedSpecType;
	}
	
	public String getSelectedSpec() {
		return selectedSpec;
	}

	public void setSelectedSpec(String selectedSpec) {
		this.selectedSpec = selectedSpec;
	}
	
	public String getSelectedDescription() {
		return selectedDescription;
	}

	public void setSelectedDescription(String selectedDescription) {
		this.selectedDescription = selectedDescription;
	}
	
	public String getSelectedName() {
		return selectedName;
	}

	public void setSelectedName(String selectedName) {
		this.selectedName = selectedName;
	}
	
	public String getSelectedFileDisplay() {
		return selectedFileDisplay;
	}

	public boolean getIsQueued() {
		return (selectedFileDisplay!=null &&  selectedFileDisplay.equalsIgnoreCase(QUEUED));
	}
	
	public boolean getIsImported() {
		return (selectedFileDisplay!=null &&  selectedFileDisplay.equalsIgnoreCase(IMPORTED));
	}

	public void setSelectedFileDisplay(String selectedFileDisplay) {
		this.selectedFileDisplay = selectedFileDisplay;
	}
	
	public void setImportSpecList(List<ImportSpecDTO> importSpecList) {
		this.importSpecList = importSpecList;
	}	
	
	public List<ImportSpecDTO> getImportSpecList() {
		return importSpecList;
	}
	
	public void setFileItemList(List<FileItem> fileItemList) {
		this.fileItemList = fileItemList;
	}	
	
	public List<FileItem> getFileItemList() {
		return fileItemList;
	}
	
	public int getRowCount() {
		if(importSpecList==null){
			return 0;
		}
		else{
			return importSpecList.size();
		}
	}
	
	private int getFirstRow() {
		if(importSpecList==null || importSpecList.size()==0){
			return 0;
		}
		else{
			return 1;
		}
	}

	private int getLastRow() {
		if(importSpecList==null || importSpecList.size()==0){
			return 0;
		}
		else{
			return importSpecList.size();
		}
	}
	
	public String getPageDescription() {		
		return String.format("Displaying rows %d through %d (%d matching rows)",
				getFirstRow(), getLastRow(), getRowCount());
	}
	
	public String getFilPageDescription() {		
		int size = 0;
		if(fileItemList!=null){
			size = fileItemList.size();
		}
		
		if(size>0){
			return String.format("Displaying rows %d through %d (%d matching rows)",1, size, size);
		}
		else{
			return String.format("Displaying rows %d through %d (%d matching rows)",0, 0, 0);
		}	
	}
	
	public int getPageSize() {
		if(importSpecList==null){
			return 0;
		}
		else{
			return importSpecList.size();
		}
	}
	
	public void selectedSpecRowChanged(ActionEvent e) throws AbortProcessingException {
		HtmlDataTable table = (HtmlDataTable) ((HtmlAjaxSupport) e.getComponent()).getParent(); 
		setSelectedSpecRowIndex(table.getRowIndex());
		selectedImportSpecDTO = (ImportSpecDTO)table.getRowData();
		
		if(selectionMap.containsKey(selectedImportSpecDTO.getImportSpecCode())){
			DatabaseItem  databaseItem  = (DatabaseItem)selectionMap.get(selectedImportSpecDTO.getImportSpecCode());	
			setSelectedDataFolder(databaseItem.getFolder());
		}
		else{
			setSelectedDataFolder("");
		}
		
		if(selectedFileDisplay.equalsIgnoreCase(QUEUED)){
			fileItemList = this.getFileNames(getQueuedFolderPath()); 
		}
		else if(selectedFileDisplay.equalsIgnoreCase(IMPORTED)){
			fileItemList = this.getFileNames(getImportedFolderPath()); 
		}
		else if(selectedFileDisplay.equalsIgnoreCase(PRESCRIPT)){
			fileItemList = this.getFileNames(getPreimportScriptFolderPath()); 
		}
		else if(selectedFileDisplay.equalsIgnoreCase(POSTSCRIPT)){
			fileItemList = this.getFileNames(getPostimportScriptFolderPath()); 
		}
		else{
			if(fileItemList!=null){
				fileItemList.clear();
			}
			fileItemList = new ArrayList<FileItem>();
		}	
		
		selectedFileRowIndex = -1;
	}
	

WebRoot/aidFileManager/AidFileManagerMain.jsp
<ui:component xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j">
      
<ui:composition template="/WEB-INF/view/templates/standard.xhtml">
<ui:define name="script">
<script type="text/javascript">
//<![CDATA[
    registerEvent(window, "load", function() { selectRowByIndex('aidFileManagerForm:specTable', 'selectedSpecRowIndex'); } );
    registerEvent(window, "load", function() { selectRowByIndex('aidFileManagerForm:fileTable', 'selectedFileRowIndex'); } );
    registerEvent(window, "load", adjustHeight);
               
//]]>
</script>

<style>
.rich-stglpanel-marker {float: left}
.rich-stglpanel-header {text-align: left}
</style>


</ui:define>
<ui:define name="body">
<f:view>
<h:inputHidden id="selectedSpecRowIndex" value="#{aidFileManagerBean.selectedSpecRowIndex}" />
<h:inputHidden id="selectedFileRowIndex" value="#{aidFileManagerBean.selectedFileRowIndex}" />
    
<h:form id="aidFileManagerForm">
     <h1><h:graphicImage id="imgAIDFileManagerMain" alt="AID&#160;File&#160;Manager" url="/images/headers/hdr-aid-file-manager.png" width="250" height="19" /></h1>
     
     <div class="tab"><h:graphicImage url="/images/containers/STSSelection-filter-open.gif" />&#160;&#160;&#160;
     	<a4j:commandLink id="toggleHideSearchPanel" style="height:22px;text-decoration: underline;color:#0033FF"
       				reRender="showhidefilter,toggleHideSearchPanel" actionListener="#{aidFileManagerBean.togglePanelController.toggleHideSearchPanel}" >
       			<h:outputText value="#{(aidFileManagerBean.togglePanelController.isHideSearchPanel) ? 'show' : 'hide'}" />
       	</a4j:commandLink>					
     </div> 
     
     <a4j:outputPanel id="showhidefilter">
     	<c:if test="#{!aidFileManagerBean.togglePanelController.isHideSearchPanel}">
	     	<div id="top">
	      	<div id="table-one">
				<a4j:outputPanel  id="contentToggle" ajaxRendered="true" layout="block">
					<a4j:include ajaxRendered="true" viewId="/WEB-INF/view/components/aid_specfile_panel.xhtml">
						<ui:param name="handlerBean" value="#{aidFileManagerBean}"/>
						<ui:param name="readonly" value="false"/>					
					</a4j:include>
				</a4j:outputPanel>
	      	</div>
	     	</div>
		</c:if>
	</a4j:outputPanel>

    <div class="wrapper">
		<span class="block-right">&#160;</span>
		<span class="block-left tab">
		<img src="../images/containers/STSSecurity-details-open.gif" />
		</span>
	</div>
    
	<!-- table-four-contentNew  -->     
	<div id="table-four-contentNew">
        
	<table cellpadding="0" cellspacing="0" style="width:auto;height:100%">
    <tbody>
	<tr>
	<td style="width: 600px;height:auto;vertical-align:top;">
 
    <div id="bottom" style="padding: 0 0 3px 0;">
    	<div id="table-four"  >
	    <div id="table-four-top" style="padding: 3px 0 0 10px;" ><h:outputText style="font-weight: bolder; color:#336699;font-size: 12px;" value="Import Specs&#160;&#160;&#160;&#160;&#160;" />
	    	<rich:modalPanel id="requestProcessed" zindex="2000" moveable="false" width="0" top="-30" height="0" left="-30" resizeable="false" />
	        <a4j:status id="pageInfo"  
					startText="Request being processed..." 
					stopText="#{aidFileManagerBean.pageDescription }"
					onstart="javascript:Richfaces.showModalPanel('requestProcessed');"
	     			onstop="javascript:Richfaces.hideModalPanel('requestProcessed');" />
	    </div>
       
        <div class="scrollInnerNew" id="resize" >
       	<rich:dataTable rowClasses="odd-row,even-row" id="specTable"  value="#{aidFileManagerBean.importSpecList}" var="importSpec"  >
           	<a4j:support id="ref2tbl"  event="onRowClick" status="rowstatus"
                        onsubmit="selectRow('aidFileManagerForm:specTable', this);"  actionListener="#{aidFileManagerBean.selectedSpecRowChanged}"
                        reRender="fileTable,downloadFile,viewFile,fileTable,fileTableDisplay,addFile,deleteFile,viewlog,reimport,fileDataTest,fileDisplayItems" />
                                  	
           	<rich:column id="importSpecType" style="width:180px;" sortBy="#{importSpec.importSpecType}">
				<f:facet name="header">
					<h:outputText styleClass="headerText" value="Import Spec Type"/>
				</f:facet>
				<h:outputText id="rowimportSpecType" value="#{importSpec.importSpecType}-#{cacheManager.listCodeMap['BATCHTYPE'][importSpec.importSpecType].description}" style="width:200px;text-align:center;"/>
			</rich:column>
           	
           	<rich:column id="importSpecCode" style="width:150px;" sortBy="#{importSpec.importSpecCode}">
				<f:facet name="header">
					<h:outputText styleClass="headerText" value="Import Spec Code"/>
				</f:facet>
				<h:outputText id="rowimportSpecCode" value="#{importSpec.importSpecCode}" style="width:200px;text-align:center;"/>
			</rich:column>
			
			<rich:column id="description" style="width:180px;" sortBy="#{importSpec.description}">
				<f:facet name="header">
					<h:outputText styleClass="headerText" value="Description"/>
				</f:facet>
				<h:outputText id="rowdescription" value="#{importSpec.description}" style="width:200px;text-align:center;"/>
			</rich:column>
           	
          </rich:dataTable>
          
          <a4j:outputPanel id="specDataTest">
          <c:if test="#{aidFileManagerBean.rowCount == 0}">
				<div class="nodatadisplay"><h:outputText value="Click Search to retrieve." /></div>
          </c:if>
          </a4j:outputPanel>
         
         </div>
         <!-- scroll-inner --> 
       <!-- end custGrid -->
       
       </div>
    </div>
	</td>
	
	<td style="width: 600px;height:auto;vertical-align:top;" >
  	<div id="bottom" style="padding: 0 0 3px 0;">
       <div id="table-four"  style="margin:0;" >
       <div id="table-four-top" style="padding: 3px 0 0 10px;"><h:outputText style="font-weight: bolder; color:#336699;font-size: 12px;" value="Display:&#160;&#160;&#160;" />
       		<h:selectOneMenu id="fileDisplayItems" style="width:130px;" value="#{aidFileManagerBean.selectedFileDisplay}" immediate="true" >
				<f:selectItems value="#{aidFileManagerBean.fileDisplayItems}"/>
				<a4j:support event="onchange" actionListener="#{aidFileManagerBean.fileDisplayChanged}" reRender="fileTable,downloadFile,viewFile,fileTableDisplay,addFile,deleteFile,viewlog,reimport"/>			
			</h:selectOneMenu>&#160;&#160;
			<h:outputText id="fileTableDisplay" style="font-size: 10px;" value="#{aidFileManagerBean.filPageDescription}" />
       </div>
       
        <div class="scrollInner"  id="resize1" >
         	<rich:dataTable rowClasses="odd-row,even-row" id="fileTable"  
         			value="#{aidFileManagerBean.fileItemList}" var="fileItem" >
           	<a4j:support id="ref2tblLocn"  event="onRowClick" status="rowstatus"
                        onsubmit="selectRow('aidFileManagerForm:fileTable', this);"  actionListener="#{aidFileManagerBean.selectedFileRowChanged}"
                        reRender="downloadFile,viewFile,fileTableDisplay,addFile,deleteFile,viewlog,reimport" />
             
            <rich:column id="selected" styleClass="column-center">        	
            	<f:facet name="header">
	            	<a4j:commandLink id="selected-a4j" value="Select"   styleClass="sort-#{aidFileManagerBean.sortOrder['selected']}"   actionListener="#{aidFileManagerBean.sortAction}"                       
	                	 oncomplete="initScrollingTables();" immediate="true" reRender="fileTable" />
	           	</f:facet>  	
            	<h:selectBooleanCheckbox styleClass="check" value="#{fileItem.selected}" disabled="#{false}" id="selectedFlagId" >
            		<a4j:support id="ajaxiCheck_selectedFlag" event="onclick" actionListener="#{aidFileManagerBean.selectTableCheckChange}" >
					</a4j:support>
            	</h:selectBooleanCheckbox>	
           	</rich:column>
        	
        	<rich:column id="fileName" styleClass="column-left">
	            <f:facet name="header">
	            	<a4j:commandLink id="fileName-a4j" value="File Name"   styleClass="sort-#{aidFileManagerBean.sortOrder['fileName']}"   actionListener="#{aidFileManagerBean.sortAction}"                       
	                	 oncomplete="initScrollingTables();" immediate="true" reRender="fileTable" />
	           	</f:facet>
	           	<h:outputText id="rowfileName" value="#{fileItem.fileName}" style="width:200px;text-align:left;"/>
        	</rich:column>
        	
        	<rich:column id="fileDate" styleClass="column-left">
	            <f:facet name="header">
	            	<a4j:commandLink id="fileDate-a4j" value="Date Modified"   styleClass="sort-#{aidFileManagerBean.sortOrder['fileDate']}"   actionListener="#{aidFileManagerBean.sortAction}"                       
	                	 oncomplete="initScrollingTables();" immediate="true" reRender="fileTable" />
	           	</f:facet>
	           	<h:outputText id="rowfileDate" value="#{fileItem.fileDate}" style="width:200px;text-align:left;">
	           		<f:converter converterId="dateTime"/>
				</h:outputText>
        	</rich:column>

			<rich:column id="fileSize" styleClass="column-left">
	            <f:facet name="header">
	            	<a4j:commandLink id="fileSize-a4j" value="Size"   styleClass="sort-#{aidFileManagerBean.sortOrder['fileSize']}"   actionListener="#{aidFileManagerBean.sortAction}"                       
	                	 oncomplete="initScrollingTables();" immediate="true" reRender="fileTable" />
	           	</f:facet>
	           	<h:outputText id="rowfileSize" value="#{fileItem.fileSize}&#160;KB" style="width:200px;text-align:left;"/>
        	</rich:column>
			 
          	</rich:dataTable>

          <a4j:outputPanel id="fileDataTest">
          		<c:if test="#{aidFileManagerBean.selectedSpecRowIndex == -1}">
					<div class="nodatadisplay"><h:outputText value="No Import Spec Selected." /></div>
          		</c:if>
           </a4j:outputPanel>
		</div>
                
       	<div id="table-four-bottom">
        <ul class="right">
        	<li class="download"><h:commandLink id="downloadFile" style="#{(aidFileManagerBean.currentUser.viewOnlyBooleanFlag)? 'display:none;':'display:block;'}" disabled="#{!aidFileManagerBean.displayDownloadButtons or aidFileManagerBean.currentUser.viewOnlyBooleanFlag}"  immediate="true" action="#{aidFileManagerBean.displayDownloadAction}" /></li>   
        	<li class="view115"><h:commandLink id="viewFile" disabled="#{!aidFileManagerBean.displayViewButtons}" immediate="true" action="#{aidFileManagerBean.displayViewAction}" /></li>
        	<li class="add"><h:commandLink id="addFile" style="#{(aidFileManagerBean.currentUser.viewOnlyBooleanFlag)? 'display:none;':'display:block;'}" disabled="#{!aidFileManagerBean.displayAddButtons or aidFileManagerBean.currentUser.viewOnlyBooleanFlag}"  immediate="true" action="#{aidFileManagerBean.displayAddAction}" /></li>
        	<li class="delete115"><a4j:commandLink id="deleteFile" style="#{!aidFileManagerBean.displayDeleteButtons? 'display:none;':'display:block;' or (aidFileManagerBean.currentUser.viewOnlyBooleanFlag)? 'display:none;':'display:block;'}" immediate="true"  
        		oncomplete="javascript:Richfaces.showModalPanel('executeDelete');" reRender="executeDeleteForm" /></li>
        	<li class="viewlog"><h:commandLink id="viewlog" disabled="#{!aidFileManagerBean.displayLogButtons}"  immediate="true" action="#{aidFileManagerBean.displayLogAction}" /></li>     	
        	<li class="reimport"><a4j:commandLink id="reimport" style="#{!aidFileManagerBean.displayReimportButtons? 'display:none;':'display:block;' or aidFileManagerBean.currentUser.viewOnlyBooleanFlag ? 'display:none;':'display:block;'}"  immediate="true" 
        	     oncomplete="javascript:Richfaces.showModalPanel('executeReimport');" reRender="executeReimportForm" /></li>
        </ul>
       	</div> 
		
      	</div>  
    </div>   
	</td>

	
	
	</tr>
	</tbody>
	</table>

	</div>
    <!-- end of table-four-contentNew  -->  
     
</h:form>
</f:view>
   
<rich:modalPanel id="executeDelete" zindex="2000" autosized="true">
	<f:facet name="header">
		<h:outputText value="Confirm Delete" />
	</f:facet>
	<h:form id="executeDeleteForm">
		<h:panelGrid columns="1" columnClasses="column-left" headerClass="column-left" cellpadding="2" cellspacing="2">
			<f:facet name="header">
				<h:outputText value="Are you sure?"/>
			</f:facet>
			
			<h:panelGroup style="text-align:center;">
				<h:commandButton id="okBtn" value="Ok"  style="cursor:pointer" onclick="Richfaces.hideModalPanel('executeDelete');" action="#{aidFileManagerBean.displayDeleteAction}" />
				<rich:spacer width="20px"/>
				<h:commandButton id="cancelBtn" style="cursor:pointer" value="Cancel" onclick="Richfaces.hideModalPanel('executeDelete'); return false;" />
			</h:panelGroup>
			
		</h:panelGrid>
	</h:form>
</rich:modalPanel>

<rich:modalPanel id="executeReimport" zindex="2000" autosized="true">
	<f:facet name="header">
		<h:outputText value="Confirm Reimport" />
	</f:facet>
	<h:form id="executeReimportForm">
		<h:panelGrid columns="1" columnClasses="column-left" headerClass="column-left" cellpadding="2" cellspacing="2">
			<f:facet name="header">
				<h:outputText value="Are you sure?"/>
			</f:facet>
			
			<h:panelGroup style="text-align:center;">
				<h:commandButton id="okBtn" value="Ok"  style="cursor:pointer" onclick="Richfaces.hideModalPanel('executeReimport');" action="#{aidFileManagerBean.displayReimportAction}" />
				<rich:spacer width="20px"/>
				<h:commandButton id="cancelBtn" style="cursor:pointer" value="Cancel" onclick="Richfaces.hideModalPanel('executeReimport'); return false;" />
			</h:panelGroup>
			
		</h:panelGrid>
	</h:form>
</rich:modalPanel>
   
</ui:define>
</ui:composition>
</ui:component>